import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import apiConfig from "../../../config/apiConfig";
import routes from "../../../routes/routes";
import { Download, Trash2, Maximize } from "lucide-react";
import StatusBadge from "../../Atoms/StatusBadge/StatusBadge";
export default function InvoiceCard({ invoice, onDelete, onDownload, onMaximize, viewOnly=false }) {
  const buttonStyle =
    "text-white rounded px-1 py-1 font-semibold hover:bg-gray-700 ";

  return (
    <>
      <div className="my-8 bg-white shadow-lg rounded-lg flex flex-col">
        <div className="flex p-1 justify-between items-center bg-yellow-500 rounded-t-lg">
          <div className="font-semibold text-white flex justify-center items-center gap-2 ml-4">
            Invoice # {invoice.id}{" "}
            <StatusBadge status={invoice.invoice_status} />
          </div>
          <div className="flex space-x-2 w-full sm:w-auto">
            <button
              className={`${buttonStyle} bg-blue-500`}
              onClick={() => onDownload(invoice.id)}
            >
              <Download />
            </button>
          
            {
                !viewOnly && (<button
                className={`${buttonStyle} bg-red-500`}
                onClick={() => onDelete(invoice.id)}
              >
                <Trash2 />
              </button>)
            }
           
            <button
              className={`${buttonStyle} bg-green-500`}
              onClick={() => onMaximize(invoice.id)}
            >
              <Maximize />
            </button>
          </div>
        </div>
        <div className="flex flex-row justify-between  w-full px-2 py-1 bg-gray-100 rounded-b-lg">
          <div className="flex flex-col justify-start items-start gap-2">
            <p className="text-md font-semibold"> {invoice.client_name} </p>
            <p className="text-sm text-gray-700">
              {" "}
              <strong>Email: </strong>{invoice?.client_email ? invoice?.client_email : "N/A"}
            </p>
            <p className="text-gray-700 text-sm">
            <strong>Generated By:</strong> {invoice?.invoice_generated_by_name}
          </p>
          <p className="text-gray-700 text-sm">
            <strong>Date Range:</strong> {invoice.date_range}
          </p>
          </div>

         

          <div className="flex flex-col p-1 justify-start items-start ">
            <p className="text-gray-700">
              <strong>Due Date:</strong> {invoice.due_date}
            </p>
            <p className="text-gray-700">
              <strong>Total Cost:</strong> €{invoice.total_cost}
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
